language: ruby

rvm:
- 2.4
- 2.5
- 2.6

cache: bundler

before_install: gem install bundler -v 2.0.1

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: doc
    verbose: true
    on:
      repo: jcouball/github_pages_rake_tasks
      rvm: 2.4

  - provider: rubygems
    api_key:
      secure: KahdMURAHsv8wRwKtAq49C2MtfK/whBXH8nZg94modg3Ke7lvJXhuvDeg+nBvMDG0OIWE8p1nEuC4QZmFfx3AXbHUVw3oajau80Z8K952ckPEJQpYUIvbx6EXu+7rA9awnYdeM1YY+6GjE62WvmSyNyCnn8HbelJSNjik/DuJLOJyEiqT16GqvZsC2bxIB5A0HUVZYfSGSJAHjrfSsI+rOzP1f05Ug99UhNhtGKaRD3sXURhjy4UOU6zHtVin8x5tJ+WlFhzuf+V5xYg9bI1n++TZLL243RqxhioNDAIZWzGcO8xQuLuAuZfXqv1dtFyf8SUF5I/xypJPJMhq9INu4OtaEqQZU6LnpG6Sm/KcgBTCKniD1pj5SCA3Je3skgP/Hxl84Zt5jdmAnSvsNKM7/eaOwqeK6Snp+fSjOZNnG+tvOP4bDoVDl68vou+Ou3VayEsfp9SQg9B8hpZ3yhLyqR6AbTrTCXIzG+Fd7vE2+ldemKx2fo5IokaEuJeKAQPxaYn9b0paCZ0URxKKv6MRosa7SO6BIlAuzqNXHmGgKWFz4n0dPoAsmHC6lW4nHR98LpgvSAOneRLomUvJ9MtQ6y1oXH8wfCYX7WkW5uQSi7cLM9gE2uz0XGxKAW8udqXbYX3LaGl6ij9nmbwCCPuuIeziTiMrQKyPotfJNlP6Sw=
    gem: github_pages_rake_tasks
    on:
      repo: jcouball/github_pages_rake_tasks
      rvm: 2.4

