language: ruby

rvm:
- 2.4
- 2.5
- 2.6

cache: bundler

before_install: gem install bundler -v 2.0.1

before_deploy:
  - echo "machine github.com\n    login jcouball\n    password ${GITHUB_TOKEN}" > ~/.netrc
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - gem install bump
  - bump patch --commit-message "[skip ci]"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: doc
    verbose: true
    on:
      branch: master
      repo: jcouball/github_pages_rake_tasks
      rvm: 2.4
  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    gem: github_pages_rake_tasks
    on:
      branch: master
      repo: jcouball/github_pages_rake_tasks
      rvm: 2.4
